apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.service-name" . }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4}}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.port }}
      name: "solr-client"
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
