{{- if .Values.initScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solr.custom-script.configmap-name" . }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
data:
{{- include "common.tplvalues.render" (dict "value" .Values.initScripts "context" $) | nindent 2 }}
{{- end }}
